spring:
  datasource:
    url: jdbc:h2:mem:ordersdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Optional: create / create-drop / update / none
    show-sql: true       # Optional: to log SQL in console
  h2:
    console:
      enabled: true
      path: /h2-console  # Optional: default is /h2-console
  application:
    name: order-service			
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

